- motd.json
First one~ Hope I did it wrong so I never will again ^_^
> VSAVJ training mode, Redearth tip

- motd.json
> Discord MOTD throuth Feb07

- motd.json
Re-added the Wiki and Global Discord links, added Latam Discord as well
> Ausf. Achse Motd changes

- motd.json
Added ssf2xjr1 Japanese Discord
> Add ssf2xjr1 Japanese Discord

- motd.json
sf2ce: added new URLs.
rotd: changed discord URL.
sfz3mix: added in motd with two URLs.
> Changes in sf2ce, rotd / added sfz3mix

- motd.json
spf2t, added in motd with 1 url
naname, added in motd with warning about no. of rounds
> Added spf2t and Naname

- motd.json
Updated 1 url in:
cybots and cybotsam
> Motd: cybots / cybotsam

- motd.json
dinore: added in motd with 1 url
nes_skartfighter: added in motd with 2 urls
mslugs hacks: added new line "\n"
> Motd: dinore and skartfighter

- motd.json
> motd: telehugs

- motd.json
> motd: snes_ultraclayfgt

- motd.json
added in motd with modified info.
> motd.json: added flycast_dc_techromancer

- motd.json
> motd: jojobanr1

- motd.json
snes_dbzhypdj: added one URL,
ps: was necessary add descriptions in each url
> motd-json update

- motd.json
added 2 URLs for fatfury3bh, kf2k3upl, kf2k3ps2, kf2k3ps2sp.
removed broken link from mk2. from others i don't know if i keep entry in json or remove completely.
> motd-json: update

- motd.json
Added info to play with adelheid and mukai
> motd: kf2k3ps2sp

- motd.json
> motd_lastbld2

- motd.json
- added sfiii3ano (4th strike for fc2 with discord and changes link)
- added Changes link for sfiii4n (4rd arrange)
> SF3 Romhacks changes

- motd.json
Couple of small edits to bring the AA motd more in line with other lobbies. Mainly added the rentry.co day 1 guide
> Ausf. Achse changes

- motd.json
updated doubledr: one URL
added: flycast_ngbc (with info), flycast_jingystm (one URL), tkdensho (one URL)
> motd update

- motd.json
updated svc, svcplus with one URL
avengrgsbh: added in motd with two URLs
sfpp: added in motd with one URL
> motd: updated svc, svcplus, avengrgsbh, sfpp

- motd.json
Hey, I just want to add the SFA3 French/EU discord ! Thanks !!
> French/EU SFA3 discord added

- motd.json
Added one URL for 'ngbc'.
Updated discord oceania for 'jojobanr1' (previous link is broken)
> motd: updated ngbc and jojobanr1

- motd.json
Red Earth & SF3 Romhack updates. new links and updated info
> Red Earth & SF3 Romhack updates

- motd.json
correct URL for colombian discord
> motd: sfiii3nr1

- motd.json
Updated french discord.
Also, fixed typo in **sfiii4fs**
> motd: fatfursp

- motd.json
Added snes_yuyufin in motd with one URL.
md_yuyusf: updated with one URL.
jojobanr1: updated with removal of 4 URLs (as Asariti request)
sf2ce: updated with 2 URLs.
sgemf: updated URL (gemini)
> motd: snes_yuyufin, md_yuyusf, jojobanr1, sf2ce

- motd.json
Add wiki link to Breakers Revenge and Extra hack
> motd: breakrev and brkrevext

- motd.json
flycast_dc_vonot: Updated with one URL + flycast menu info
md_yuyusf, snes_yuyufin: Updated URL (Servidor Brasileiro)
> motd: dc_vonot

- motd.json
updated discord link (Mage request)
> motd: flycast_jingystm

- motd.json
flycast_dc_gram2000: Added in motd with one URL.
snes_issdxu: Added in motd with two URLs.
samsh5sp: Adde one url (ss5s league).
> motd update: flycast_dc_gram2000

- motd.json
sfiii3nr1: Added new URLs for Russian-CIS and Chilean discord
flycast_dc_vonot: upd descriptions
Added movelist showcase for: kof94, garou, vsavj, mk, breakrev, cybots, kof97.
> motd: updated

- motd.json
> red earth motd update

- motd.json
> motd: flycast_gram2000

- motd.json
Added one URL (movelist showcase)
> motd: nes_skartfighter

- motd.json
bitly link didn't work anymore
> 4rd strike lobby link update

- motd.json
Red Earth Password Notation Update
> Red Earth Update motd.json

- motd.json
removed unnecessary comma, and also added a notification if a person has an issue launching a game
> Red Earth motd update motd.json

- motd.json
ssf2tnl <1024 characters
sfz3mix13
mslug hacks
karnovre
xmvsfu
xmvsfjr3
pbobblen
kof94te
mtlchamp
md_umk3osc
md_fatfuryu
flycast_dc_doa2_le
flycast_dc_soulclbr
nes_pentablocat
snes_fatfuryu
> motd update - various

- motd.json
kof94te: info as requested by [AliceMSU]
> motd - updates
